// solid-start/src/components/todo.tsx
import type { JSX } from 'solid-js'
import { useAction, useSubmission } from '@solidjs/router'
import { deleteTodo, updateTodo } from '~/lib/data'

export function Todo({ id, done, children }: { id: string; done: boolean; children: JSX.Element }) {
	const updateAction = useAction(updateTodo.with(id))
	const submission = useSubmission(deleteTodo)

	return (
		<li class="bg-neutral-900 rounded-lg px-4 dark:shadow-lg">
			<form action={deleteTodo.with(id)} method="post" class="flex items-center">
				<label class="grow flex gap-2 items-center h-12">
					<input type="checkbox" name="done" checked={done} onchange={() => updateAction(!done)} />
					<span>{children}</span>
				</label>

				<button
					class="p-2 rounded-md dark:bg-neutral-800 sm:text-sm inline-flex items-center -mx-2 disabled:opacity-50"
					disabled={submission.pending && id === submission.input[0]}
				>
					<span class="size-4">x</span>
				</button>
			</form>
		</li>
	)
}

// react-next/src/components/todo.tsx
'use client'

import { useOptimistic, startTransition, useActionState } from 'react'
import { toggleTodo, deleteTodo } from '@/lib/server/actions'
import { Trash } from './trash'

export function Todo({ id, content, isDone }: { id: string; content: string; isDone: boolean }) {
	const [optimisticDone, toggleOptimistic] = useOptimistic(isDone)
	const [, deleteAction, isPending] = useActionState(deleteTodo, null)

	return (
		<form className="py-2 pl-4 pr-2 rounded-lg shadow-lg flex gap-4 items-center border-zinc-800 border hover:border-zinc-600 has-checked:opacity-50">
			<input type="hidden" name="todoId" value={id} />
			<input
				id={id}
				type="checkbox"
				checked={optimisticDone}
				onChange={() => {
					startTransition(async () => {
						toggleOptimistic(!isDone)
						await toggleTodo(id, !isDone)
					})
				}}
				className="peer"
			/>
			<label htmlFor={id} className="grow peer-checked:line-through">
				{content}
			</label>
			<button
				formAction={deleteAction}
				className="p-2 bg-zinc-800 hover:bg-zinc-700 rounded-md disabled:opacity-50"
				disabled={isPending}
			>
				<Trash />
			</button>
		</form>
	)
}
